apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "marketdata.fullname" . }}
  labels:
    {{- include "marketdata.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspnetcoreEnvironment | quote }}
  JwtSettings__Issuer: {{ .Values.config.jwtIssuer | quote }}
  JwtSettings__Audience: {{ .Values.config.jwtAudience | quote }}
  Cors__AllowedOrigins: {{ .Values.config.corsAllowedOrigins | quote }}
  MarketDataProcessing__Simulation__Enabled: {{ .Values.config.enableSimulation | quote }}
  MarketDataProcessing__UsePersistentRepositories: {{ .Values.config.enablePersistentStorage | quote }}
  IpRateLimiting__EnableEndpointRateLimiting: {{ .Values.config.enableRateLimiting | quote }}
